<?php

declare(strict_types=1);

namespace App\Ai\OpenAi\Client;

use GuzzleHttp\Psr7\MultipartStream;
use Psr\Http\Message\StreamInterface;

/**
 * Builds the multipart/form-data body for a Files API upload.
 *
 * The file is passed as a stream, so a large PDF is transmitted without being read into memory. The
 * boundary is generated by the stream and reflected in the content type the caller must set.
 */
final readonly class MultipartFileUpload
{
    /**
     * @return array{stream: StreamInterface, contentType: string}
     */
    public function build(StreamInterface $file, string $filename, string $purpose): array
    {
        $stream = new MultipartStream([
            ['name' => 'purpose', 'contents' => $purpose],
            ['name' => 'file', 'contents' => $file, 'filename' => $filename],
        ]);

        return [
            'stream' => $stream,
            'contentType' => 'multipart/form-data; boundary=' . $stream->getBoundary(),
        ];
    }
}
