#!/usr/bin/env bash
#
# pull.sh — pull the Knowledge Forge changes from the live server into this local project.
#
# Run this FROM your local project root:
#     chmod +x pull.sh
#     ./pull.sh                # dry run: shows exactly what would change, writes nothing
#     ./pull.sh --apply        # takes a timestamped backup, then applies
#
# What it syncs:  src/  config/  tests/  assets/  .env.example
# What it NEVER touches:  .env  vendor/  runtime/  public/assets/  .git/
#
# Your local .env is deliberately left alone — see the NEXT STEPS printed at the end,
# because two of the fixes only take effect once you set those values yourself.

set -euo pipefail

# ─── Configure these two lines ────────────────────────────────────────────────
REMOTE_SSH="joymeal"
REMOTE_PATH="/opt/web/sites/joymeal.seawolf.io/knowledge-forge"
# ──────────────────────────────────────────────────────────────────────────────

LOCAL_PATH="/var/www/html/knowledge-forge"
STAMP="$(date +%Y%m%d_%H%M%S)"
BACKUP_DIR="$LOCAL_PATH/runtime/backups/pull_from_live_$STAMP"

APPLY=0
[ "${1:-}" = "--apply" ] && APPLY=1

# Paths that get synced. Directories only — no --delete, so nothing local is ever removed.
PATHS=(src config tests assets .env.example)

# Never pull these. .env holds YOUR local credentials and base path; vendor/runtime are
# environment-specific; public/assets is regenerated by the app on first page render.
EXCLUDES=(
  --exclude='.env'
  --exclude='envbackup.txt'
  --exclude='vendor/'
  --exclude='runtime/'
  --exclude='public/assets/'
  --exclude='.git/'
  --exclude='node_modules/'
  --exclude='tests/_output/'
  --exclude='.merge-plan.php'
)

say()  { printf '\n\033[1m%s\033[0m\n' "$*"; }
fail() { printf '\033[31mERROR: %s\033[0m\n' "$*" >&2; exit 1; }

# ─── Sanity checks ────────────────────────────────────────────────────────────
[ "$REMOTE_SSH" = "user@your-server" ] && fail "Edit REMOTE_SSH at the top of this script first."
[ -d "$LOCAL_PATH" ] || fail "Local project not found at $LOCAL_PATH"
[ -f "$LOCAL_PATH/composer.json" ] || fail "$LOCAL_PATH does not look like the project (no composer.json)"
command -v rsync >/dev/null || fail "rsync is not installed."

ssh -o BatchMode=yes -o ConnectTimeout=10 "$REMOTE_SSH" "test -f '$REMOTE_PATH/composer.json'" \
  || fail "Cannot reach $REMOTE_SSH:$REMOTE_PATH over SSH (check the host, your key, and the path)."

cd "$LOCAL_PATH"

# ─── Dry run ──────────────────────────────────────────────────────────────────
if [ "$APPLY" -eq 0 ]; then
  say "DRY RUN — nothing will be written. These files differ from live:"
  rsync -rlvn --itemize-changes "${EXCLUDES[@]}" \
    $(printf "%s:%s/%s " "$REMOTE_SSH" "$REMOTE_PATH" "${PATHS[@]}" | sed "s|$REMOTE_SSH:|$REMOTE_SSH:|g") \
    . 2>/dev/null | grep -E '^[<>ch.]' || echo "  (no differences)"
  say "Re-run with --apply to take a backup and write these changes."
  exit 0
fi

# ─── Backup ───────────────────────────────────────────────────────────────────
say "1/5  Backing up the local files that will be overwritten"
mkdir -p "$BACKUP_DIR"
for p in "${PATHS[@]}"; do
  [ -e "$p" ] && cp -a "$p" "$BACKUP_DIR/" 2>/dev/null || true
done
echo "     $BACKUP_DIR"

# ─── Sync ─────────────────────────────────────────────────────────────────────
say "2/5  Pulling from live"
for p in "${PATHS[@]}"; do
  if [ "$p" = ".env.example" ]; then
    rsync -av "${EXCLUDES[@]}" "$REMOTE_SSH:$REMOTE_PATH/.env.example" ./
  else
    # Trailing slash on the source keeps the directory name rather than nesting it.
    rsync -av "${EXCLUDES[@]}" "$REMOTE_SSH:$REMOTE_PATH/$p/" "./$p/"
  fi
done

# ─── Autoload ─────────────────────────────────────────────────────────────────
say "3/5  Refreshing the autoloader (20 new classes were added)"
if command -v composer >/dev/null; then
  composer dump-autoload -q && echo "     done"
else
  echo "     composer not found — run 'composer dump-autoload' yourself, or the new classes will not load."
fi

# ─── Syntax check ─────────────────────────────────────────────────────────────
say "4/5  Syntax-checking the pulled PHP"
errors=0
while IFS= read -r f; do
  php -l "$f" >/dev/null 2>&1 || { echo "     PARSE ERROR: $f"; errors=$((errors+1)); }
done < <(find src config -name '*.php' -type f)
[ "$errors" -eq 0 ] && echo "     all files parse cleanly" || fail "$errors file(s) failed to parse — restore from $BACKUP_DIR"

# ─── Runtime dirs the new page needs ──────────────────────────────────────────
say "5/5  Ensuring runtime/cache exists (the usage dashboard writes its snapshot there)"
mkdir -p runtime/cache runtime/logs
chmod 2775 runtime/cache runtime/logs 2>/dev/null || true
echo "     ok"

# ─── Next steps ───────────────────────────────────────────────────────────────
cat <<'NEXT'

──────────────────────────────────────────────────────────────────────────────
DONE. Two manual steps remain — the code alone is not enough.

1. ADD THESE TO YOUR LOCAL .env  (your .env was deliberately NOT overwritten,
   because it holds your own DB credentials, API key and APP_BASE_PATH).

   Without these, the chat fix does nothing: the old 1200-token budget is what
   caused broad questions to fail in the first place.

       CHAT_MAX_OUTPUT_TOKENS=4000
       OPENAI_FILE_SEARCH_MAX_RESULTS=20
       OPENAI_CHAT_TIMEOUT_SECONDS=90
       OPENAI_CHAT_MAX_RETRIES=0
       CHAT_REASONING_EFFORT=low

   Keep CHAT_REQUIRE_CITATIONS=true.

   Optional, and only for the usage dashboard's organization billing section.
   Leave it blank unless you actually have an ORGANIZATION admin key:

       OPENAI_ADMIN_API_KEY=

2. VERIFY

       php yii kf:health
       php -S localhost:8080 -t public public/index.php    # or your usual vhost

   Then, logged in as an admin, open:  /admin/openai-usage
   (no menu link — it is reachable by direct URL only, by design)

   If you have dev dependencies installed locally:

       composer install
       vendor/bin/codecept run Unit
       vendor/bin/codecept run Functional
       vendor/bin/psalm

TO UNDO: your previous files are in
NEXT
echo "    $BACKUP_DIR"
echo "──────────────────────────────────────────────────────────────────────────────"
