<?php

declare(strict_types=1);

namespace App\Document\Application\Storage;

/**
 * Where original uploads live. A port, so local disk can later be swapped for S3 without touching the
 * upload service.
 *
 * The contract is deliberately path-based and streaming: the caller captures the upload into a
 * temporary file, the storage validates and moves it into place, and reads happen by absolute path.
 * Nothing here ever takes a user-supplied name — stored names are generated by the caller.
 */
interface DocumentStorageInterface
{
    /**
     * Creates an empty temporary file on the SAME filesystem as final storage (so the later move is an
     * atomic rename, not a copy) and returns its absolute path.
     */
    public function createTemporaryFile(): string;

    /**
     * Moves a temporary file into permanent storage for a knowledge base.
     *
     * @param string $storedFilename A safe, generated name (token + extension) — never user input.
     *
     * @return string The path relative to the storage root, to persist on the document row.
     */
    public function moveInto(string $temporaryAbsolutePath, int $knowledgeBaseId, string $storedFilename): string;

    /**
     * Removes a temporary file if it still exists (cleanup after a failed upload). Never throws.
     */
    public function discard(string $temporaryAbsolutePath): void;

    /**
     * Deletes a stored file by its relative path. A path that resolves outside the storage root is
     * refused. Missing files are ignored.
     */
    public function delete(string $relativePath): void;

    /**
     * Resolves a stored relative path to an absolute one, guaranteed to be inside the storage root.
     *
     * @throws \App\Document\Application\Storage\StoragePathException when the path escapes the root.
     */
    public function absolutePath(string $relativePath): string;

    public function exists(string $relativePath): bool;

    /**
     * Opens a stored file for reading as a stream, so a large document is uploaded to the provider
     * without being read into memory.
     *
     * @throws StoragePathException when the path escapes the root or the file is missing.
     */
    public function readStream(string $relativePath): \Psr\Http\Message\StreamInterface;

    /**
     * Writes derived content (e.g. extracted Markdown) at the given relative path, creating directories
     * as needed, and returns the path. Refuses a path that escapes the root.
     */
    public function putContents(string $relativePath, string $contents): string;

    /**
     * The relative path where a document's derived Markdown is stored, alongside but distinct from the
     * original upload.
     */
    public function derivedMarkdownPath(int $knowledgeBaseId, string $storageToken): string;
}
