<?php

declare(strict_types=1);

namespace App\Document\Application\Storage;

use App\Shared\Domain\Exception\DomainException;

/**
 * A stored path could not be resolved safely — it escaped the storage root, or the root is missing.
 *
 * Treated as an internal error (not a user-facing validation message): stored paths are generated by
 * the application, so this firing means data corruption or a bug, not bad user input.
 */
final class StoragePathException extends DomainException
{
    public function errorCode(): string
    {
        return 'storage_path_invalid';
    }
}
