<?php

declare(strict_types=1);

namespace App\Document\Infrastructure;

use App\Document\Application\Storage\DocumentStorageInterface;
use App\Document\Application\Storage\StoragePathException;
use App\Shared\Infrastructure\Storage\StoragePaths;
use GuzzleHttp\Psr7\Utils;
use Psr\Http\Message\StreamInterface;

use function bin2hex;
use function dirname;
use function fopen;
use function file_put_contents;
use function is_dir;
use function is_file;
use function ltrim;
use function mkdir;
use function random_bytes;
use function rename;
use function rtrim;
use function str_contains;
use function str_starts_with;
use function unlink;

/**
 * Stores uploads on the local filesystem, under the storage root and entirely outside `public/`.
 *
 * Two defences run on every path that leaves this class:
 *
 * - Stored names are generated by the caller (token + extension), never derived from user input, so the
 *   name itself can never contain a traversal sequence.
 * - Any relative path handed back in (delete, absolutePath) is rejected outright if it contains `..` and
 *   is re-checked to be a prefix of the resolved root, so even a corrupted database value cannot make
 *   this class touch a file outside the root.
 */
final readonly class LocalDocumentStorage implements DocumentStorageInterface
{
    public function __construct(
        private StoragePaths $paths,
    ) {}

    public function createTemporaryFile(): string
    {
        $dir = $this->documentRoot() . '/tmp';
        $this->ensureDirectory($dir);

        $path = $dir . '/' . bin2hex(random_bytes(16)) . '.tmp';
        // Create the file so the later stream copy has a target, and so a token collision is visible.
        if (@file_put_contents($path, '') === false) {
            throw new StoragePathException('Could not create a temporary file in storage.');
        }

        return $path;
    }

    public function moveInto(string $temporaryAbsolutePath, int $knowledgeBaseId, string $storedFilename): string
    {
        // The stored name is generated by the caller; guard anyway against a separator sneaking in.
        if (str_contains($storedFilename, '/') || str_contains($storedFilename, '\\') || str_contains($storedFilename, "\0")) {
            throw new StoragePathException('Refusing to store a file with an unsafe name.');
        }

        $relativeDir = 'knowledge-bases/' . $knowledgeBaseId . '/documents';
        $absoluteDir = $this->documentRoot() . '/' . $relativeDir;
        $this->ensureDirectory($absoluteDir);

        $absoluteTarget = $absoluteDir . '/' . $storedFilename;

        if (!@rename($temporaryAbsolutePath, $absoluteTarget)) {
            throw new StoragePathException('Could not move the uploaded file into storage.');
        }

        return $relativeDir . '/' . $storedFilename;
    }

    public function discard(string $temporaryAbsolutePath): void
    {
        if (is_file($temporaryAbsolutePath)) {
            @unlink($temporaryAbsolutePath);
        }
    }

    public function delete(string $relativePath): void
    {
        $absolute = $this->absolutePath($relativePath);

        if (is_file($absolute)) {
            @unlink($absolute);
        }
    }

    public function absolutePath(string $relativePath): string
    {
        $relativePath = ltrim($relativePath, '/');

        // A stored path is always composed by this application; a `..` in it means corruption or an
        // attack, so refuse rather than resolve it.
        if ($relativePath === '' || str_contains($relativePath, '..') || str_contains($relativePath, "\0")) {
            throw new StoragePathException('Refusing to resolve an unsafe storage path.');
        }

        $root = $this->documentRoot();
        $absolute = $root . '/' . $relativePath;

        // Belt and braces: the resolved path must be inside the root even after normalisation.
        if (!str_starts_with($absolute, $root . '/')) {
            throw new StoragePathException('Resolved storage path escaped the storage root.');
        }

        return $absolute;
    }

    public function exists(string $relativePath): bool
    {
        return is_file($this->absolutePath($relativePath));
    }

    public function readStream(string $relativePath): StreamInterface
    {
        $absolute = $this->absolutePath($relativePath);
        $handle = @fopen($absolute, 'rb');
        if ($handle === false) {
            throw new StoragePathException('Could not open the stored file for reading.');
        }

        return Utils::streamFor($handle);
    }

    public function putContents(string $relativePath, string $contents): string
    {
        $absolute = $this->absolutePath($relativePath);
        $this->ensureDirectory(dirname($absolute));

        if (@file_put_contents($absolute, $contents) === false) {
            throw new StoragePathException('Could not write derived content to storage.');
        }

        return $relativePath;
    }

    public function derivedMarkdownPath(int $knowledgeBaseId, string $storageToken): string
    {
        return 'knowledge-bases/' . $knowledgeBaseId . '/derived/' . $storageToken . '.md';
    }

    private function documentRoot(): string
    {
        return rtrim($this->paths->documentRoot, '/');
    }

    private function ensureDirectory(string $dir): void
    {
        if (!is_dir($dir) && !@mkdir($dir, 0775, true) && !is_dir($dir)) {
            throw new StoragePathException('Could not create a storage directory.');
        }
    }
}
